<?php // -*-mode: PHP; coding:utf-8;-*-
// $Id$

function print_theme_footer()
{
?>
  </div>
  <div class="copy-right">
				<p>
				<a href="https://twitter.com/mysmartcourt" target="_blank"><i> <img src="images/tweets.png" alt="" /></i></a>
				<a href="https://www.facebook.com/mysmartcourt/" target="_blank"><i> <img src="images/facebook.png" alt="" /></i></a>
				<a href="http://www.mysmartcourt.com" target="_blank">© 2016 SMART COURT</a>
					</p>
	 	 </div>  
  
</body>
</html>
<?php

}
 